# Broadcasting
Для успешного выполнения векторизованных вычислений между двумя массивами необходимо, чтобы их размеры соответствовали друг другу. Если массивы разных размеров, то NumPy применяет ряд правил, чтобы успешно выпонить вычисление. Набор этих правил называются [**broadcasting**.](https://docs.scipy.org/doc/numpy-1.13.0/user/basics.broadcasting.html)

Рассмотрим следующий пример, в котором к массиву добавляется скалярное значение

In [1]:
import numpy as np

In [4]:
x = np.arange(2)
x + 10

array([10, 11])

В данном случае этот код фактически эквиваленптен следующему, в котором вмсесто числа 10 используется другой массив такого же размера как и массив `x` заполненный значениями 10

In [5]:
y = np.full(2, 10)
x + y

array([10, 11])

Точно также одномерный массив может быть "расстянут" для сложения с двумерным массивом

In [8]:
z = np.full(shape=(2, 2), fill_value=10)
z + x

array([[10, 11],
       [10, 11]])

При применении broadcasting размер обоих массивов может быть изменен. Например, если один массив содержит одну строку, а второй одну колонку

In [11]:
x = np.arange(3)
y = np.arange(3)[:, np.newaxis]

print(x)
print(y)

[0 1 2]
[[0]
 [1]
 [2]]


In [12]:
x + y

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

В данном случае оба массива выли "расстянуты", чтобы размер обоих соответсвовал друг другу. 

Broadcasting можно визуализировать следующей картинкой

![Broadcasting Visual](img/numpy-broadcasting.png)

Прозрачные кубики соответствуют "расстянутым" частям массива. Нужно отметить, что broadcasting физически не создает новые элементы массива и не занимает дополнительной памяти, это всего лишь концептуальное представление этих правил.

## Правила Broadcasting
При выполнении арифметических операций между двумя массивами NumPy проверяет размеры каждого измерения по очереди начиная с конца. Два измерения считаются совместимыми если

1. Если их размеры совпадают
2. Размер измерения одного из них равен 1

Если размер измерения первого массива равен 1, то значения этого измерения будут продублированы, чтобы соответствовать измерению второго массива. Итоговый массив будет содержать максимальный размер по каждому из измерений. Например, если сложить два массива размерами `2 x 1 x 3` и `2 x 5 x 1`, итоговый массив будет иметь размер `2 x 5 x 3`.

Стоит отметить, что количество измерений не должно быть одинаковым в обоих массивах. Так как сранвение измерений идет с конца, то именно эти последние измерения должны соответствовать друг другу

In [19]:
M1 = np.ones(shape=(2, 1, 3))
M2 = np.ones(shape=(2, 5, 1))
print('M1      shape:', M1.shape)
print('M2      shape:', M2.shape)
print('M1 + M2 shape:', (M1 + M2).shape)

M1      shape: (2, 1, 3)
M2      shape: (2, 5, 1)
M1 + M2 shape: (2, 5, 3)


Стоит отметить, что количество измерений не должно быть одинаковым в обоих массивах. Так как сранвение измерений идет с конца, то именно эти последние измерения должны соответствовать друг другу. 

Если измерения двух массивов не соответствуют друг другу, то выйдет ошибка `ValueError: operands could not be broadcast together with shapes`

In [26]:
M = np.ones((2, 2))
x = np.arange(3)
M + x

ValueError: operands could not be broadcast together with shapes (3,2) (3,) 

Остальные примеры можно найти в [официальной доументации](https://docs.scipy.org/doc/numpy-1.13.0/user/basics.broadcasting.html)

# Логические операции
