# Broadcasting
Для успешного выполнения векторизованных арифметических операций между двумя массивами необходимо, чтобы их размеры соответствовали друг другу. Если массивы разных размеров, то NumPy применяет ряд правил, чтобы успешно выпонить вычисление. Набор этих правил называются [**broadcasting**.](https://docs.scipy.org/doc/numpy-1.13.0/user/basics.broadcasting.html)

Рассмотрим следующий пример, в котором к массиву добавляется скалярное значение

In [1]:
import numpy as np

In [2]:
x = np.arange(2)
x + 10

array([10, 11])

В данном случае этот код фактически эквиваленптен следующему, в котором вмсето числа 10 используется другой массив такого же размера как и массив `x` заполненный значениями 10

In [3]:
y = np.full(x.shape, 10)
x + y

array([10, 11])

Точно также одномерный массив может быть "расстянут" для сложения с двумерным массивом

In [4]:
z = np.full(shape=(2, 2), fill_value=10)
z + x

array([[10, 11],
       [10, 11]])

При применении broadcasting размер обоих массивов может быть изменен. Например, если один массив содержит одну строку, а второй одну колонку

In [5]:
x = np.arange(3)
y = np.arange(3)[:, np.newaxis]

print(x)
print(y)

[0 1 2]
[[0]
 [1]
 [2]]


In [6]:
x + y

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

В данном случае оба массива выли "расстянуты", чтобы размер обоих соответсвовал друг другу. 

Broadcasting можно визуализировать следующей картинкой

![Broadcasting Visual](img/numpy-broadcasting.png)

Прозрачные кубики соответствуют "расстянутым" частям массива. Нужно отметить, что broadcasting физически не создает новые элементы массива и не занимает дополнительной памяти, это всего лишь концептуальное представление этих правил.

## Правила Broadcasting
При выполнении арифметических операций между двумя массивами NumPy проверяет размеры каждого измерения по очереди начиная с конца. Два измерения считаются совместимыми если

1. Если их размеры совпадают
2. Размер измерения одного из них равен 1

Если размер измерения одного массива равен 1, то значения этого измерения будут продублированы, чтобы соответствовать измерению другого массива. Итоговый массив будет содержать максимальный размер по каждому из измерений. Например, если сложить два массива размерами `2 x 1 x 3` и `2 x 5 x 1`, итоговый массив будет иметь размер `2 x 5 x 3`

In [7]:
M1 = np.ones(shape=(2, 1, 3))
M2 = np.ones(shape=(2, 5, 1))
print('M1      shape:', M1.shape)
print('M2      shape:', M2.shape)
print('M1 + M2 shape:', (M1 + M2).shape)

M1      shape: (2, 1, 3)
M2      shape: (2, 5, 1)
M1 + M2 shape: (2, 5, 3)


Стоит отметить, что количество измерений не должно быть одинаковым в обоих массивах. Так как сранвение измерений идет с конца, то именно эти последние измерения должны соответствовать друг другу. 

Если измерения двух массивов не соответствуют друг другу, то выйдет ошибка `ValueError: operands could not be broadcast together with shapes`

In [8]:
M = np.ones((2, 2))
x = np.arange(3)
M + x

ValueError: operands could not be broadcast together with shapes (2,2) (3,) 

Остальные примеры можно найти в [официальной доументации](https://docs.scipy.org/doc/numpy-1.13.0/user/basics.broadcasting.html)

# Логические операции
До этого мы рассмотрели векторизованные вычисления применительно к арифметическим операторам. С помощью векторизованных вычислений и правил broadcasting мы можем применять арифметический оператор каждой соответствующей паре элементов массивов. Точно также можно использовать логические операторы (`==`, `!=`, `>`, `<`, `>=`, `<=`) для векторизованных вычислений

In [9]:
x = np.arange(1, 6)

In [10]:
x < 3

array([ True,  True, False, False, False], dtype=bool)

В результате применения логического оператора получается массив с булевым (boolean) типом

In [11]:
x != 3

array([ True,  True, False,  True,  True], dtype=bool)

In [12]:
x == 1

array([ True, False, False, False, False], dtype=bool)

Можно комбинировать выражения

In [13]:
(x % 2) == 0

array([False,  True, False,  True, False], dtype=bool)

In [14]:
(2 % x) == (x // 2)

array([ True, False, False,  True,  True], dtype=bool)

Логические операторы также работаю с многомерными массивам

In [15]:
x = np.arange(16).reshape((4, 4))
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [16]:
x >= 8

array([[False, False, False, False],
       [False, False, False, False],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]], dtype=bool)

## Агрегирование булевых массивов
Существуют ряд функций, которые предназначены для агрегирования булевых массивов. Например, функция `np.sum`, которая считает `True` за единицу, а `False`. Так мы можем посчитать количество элементов со значением `True` в массиве

In [17]:
np.sum(x >= 8)

8

Как и для обычных агрегирующих функций, можно использовать параметр `axis` для агрегирования по заданному измерению

In [18]:
np.sum(x >= 8, axis=0)

array([2, 2, 2, 2])

Для проверки, является ли хотя бы один или все элементы массива `True`, можно использовать функции `np.any` и `np.all` соответственно

In [19]:
np.any(x >= 8)

True

In [ ]:
np.all(x >= 8)

In [20]:
np.any(x < 0)

False

In [21]:
np.all(x >= 0)

True

Как и другие агрегирующие функции вызове `np.any` и `np.all` для многомерных массивов можно указать параметр `axis`

In [22]:
np.any((x % 2) == 1, axis=0)

array([False,  True, False,  True], dtype=bool)

In [ ]:
np.all((x % 2) == 1, axis=0)

## Комбинирование булевых массивов с помощью логических операторов
Во всех языках программирования можно комбинировать булевые выражения с помощью логических операторов. Например в Python для этого используюся ключевые слова `not`, `and`, `or`. NumPy поддерживает такие операции с помощью побитных операторов 
+ **`&`** - логический оператор **И** (AND)
+ **`|`** - логический оператор **ИЛИ** (OR)
+ **`^`** - исключающее **ИЛИ** (XOR)
+ **~** - логическое отрицание **НЕ** (NOT)

Например, мы можем найти количество чисел между 3 и 9

In [23]:
np.sum((x >= 3) & (x <= 9))

7

Или количество чисел вне диапазона 3 и 9

In [24]:
np.sum(~((x >= 3) & (x <= 9)))

9

Необходимо помнить, что приоритет логических операторов выше приоритета операторов сравнения. Следующий код выдаст ошибку так как вычисляет выражение `x >= (3 & x) <= 9`

In [25]:
x >= 3 & x <= 9

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

Поэтому не забывайте ставить скобки когда пишете сложные логические выражения

## Булевые маски для фильрации
В NumPy булевые массивы чаще всего используются как маски для выбора нужных элементов массива. Это очень мощный способ работы с массивами. Давайте выберем все числа массива, кратные трем

In [26]:
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [27]:
(x % 3) == 0

array([[ True, False, False,  True],
       [False, False,  True, False],
       [False,  True, False, False],
       [ True, False, False,  True]], dtype=bool)

In [28]:
x[(x % 3) == 0]

array([ 0,  3,  6,  9, 12, 15])

Можно строить сколь угодно сложные выражения и использовать их в качестве фильтра. Ниже приведен пример, который выбирает все четные числа между 3 и 9

In [29]:
mask = x >= 3
mask = mask & (x <= 9)
mask = mask & ((x % 2) == 0)
x[mask]

array([4, 6, 8])