# Основные понятия линейной алгебры
В даннном материале мы рассмотрим основные понятия линейной алгебры, которые необходимы для понимания основ машинного обучения. 
Основными понятиями линейной алгебры являются векторы и матрицы. Основные операции линейной алгебры определяются с помощью линейных отображений. Во многом именно линейные отображения делают линейную алгебру столь важной для прикладных задач. 

## Почему линейная алгебра столь важна?
Окружающий нас мир очень сложен и многие его проблемы имеют нелинейную природу. Изучение и понимание этих нелинейных связей в природе и в технике крайне сложно. Из-за этого инженеры, вместо того чтобы напрямую работать с нелинейными моделями, часто прибегают к линейным приблежениям этих моделей. Для этого нелинейную модель разбивают на многие меньшие части, где каждая часть в отдельности очень хорошо апроксимируется (т.е. приближается) линейным отображением. Как только проблема сформулирована в виде линейных отображений, сразу появляется возможность решить её очень эффективно и быстро с помощью методов линейной алгебры. 

В данном материале будут даны лишь общие понятия, описание терминов и некоторые теоремы без доказательств. Для более глубокого изучения нужно обратиться к специализированным курсам по линейной алгебре.

## Скалярная величина (scalar) 
Скалярная величина — величина, каждое значение которой может быть выражено одним действительным числом. Другими словами любое действительное число является скалярным значением. Термин появился в физике для обозначения величин, значения которых может быть выражено одним числом (длина, площадь, время, температура и т. д.), в отличии от других величин, которые выражаются с помощью векторов (например, сила имеет не только величину, но и направление). Скалярное значение обозначается маленькими буквами греческого (например, $\alpha$, $\beta$, $\gamma$) или латинского (например, a, b, c) алфавитов.

## Вектор (vector)
Вектором размера n мы будем называть одномерный массив из n чисел. Для обозначения вектора используется буква латинского алфавита со стрелочкой $\vec{x}$. Для записи вектора вместе с элементами в столбец используется следующая нотация
$$
\begin{align}
\vec{x} &= \begin{bmatrix}
        x_{1} \\
        x_{2} \\
        \vdots \\
        x_{n}
     \end{bmatrix}
\end{align}
$$
Вместо записи в столбец, веткор может быть записан в виде строки следующим образом:
1. $\vec{x} = (x_1, x_2, \ldots, x_n)$
2. $\vec{x} = \left<x_1, x_2, \ldots, x_n\right>$

Каждый элемент вектора является действительным числом. Для обозначения этого свойства используется нотация $x_i \in \mathbb{R}$, где $\mathbb{R}$ обозначает множество действительных чисел, а символ $\in$ принадлежность к данному множеству. Для обозначения того, что вектор размера n состоит из действительных чисел исопльзуется нотация $\vec{x} \in \mathbb{R^n}$.

В python мы будем использовать библиотеку NumPy для работы с векторами. Как было сказано выше, вектор размера n это одномерный массив с n числами. В NumPy мы можем создать $\vec{x} = (1, 2, 3)$ следующим образом

In [1]:
import numpy as np

np.array([1, 2, 3])

array([1, 2, 3])

### Стандартный (базисный) единичный вектор (standard (basis) unit vector)
Стандартным или базисным единичным вектором называются векторы размера n, у которых один элемент равен 1, а все остальные 0. У стандартного вектора $\vec{e_j}$ элемент на позиции j равен 1, а все остальные позиции равны 0:
$$
\begin{align}
\vec{e_j} &= \begin{bmatrix}
        0 \\
        \vdots \\
        0 \\
        1 \\
        0 \\
        \vdots \\
        0
     \end{bmatrix}
\end{align}
$$
Единичные векторы в двухмерном пространстве обозначаются как $\hat{i}$ и $\hat{j}$
$$
\begin{align}
\hat{i}=\vec{e_0} &= \begin{bmatrix}
        1 \\
        0
     \end{bmatrix} &
\hat{j}=\vec{e_1} &= \begin{bmatrix}
        0 \\
        1
     \end{bmatrix}
\end{align}
$$
Единичные векторы в трехмерном пространстве обозначаются как $\hat{i}$, $\hat{j}$ и $\hat{k}$
$$
\begin{align}
\hat{i}=\vec{e_0} &= \begin{bmatrix}
        1 \\
        0 \\
        0
     \end{bmatrix} &
\hat{j}=\vec{e_1} &= \begin{bmatrix}
        0 \\
        1 \\
        0
     \end{bmatrix} &
\hat{k}=\vec{e_2} &= \begin{bmatrix}
        0 \\
        0 \\
        1
     \end{bmatrix}
\end{align}
$$
Стандартный единичный вектор имеет важное значение, которое мы увидем далее. Ниже приведен пример создания единичных векторов в трехмерном прастранстве с помощью NumPy

In [2]:
i = np.array([1, 0, 0])
j = np.array([0, 1, 0])
k = np.array([0, 0, 1])
i, j, k

(array([1, 0, 0]), array([0, 1, 0]), array([0, 0, 1]))

### Умножение вектора на скалярное значение
При умножении вектора на скалярное значение каждый элемент этого вектора умножается на скалярное значение. Например, если мы хотим скалярное значение $\alpha$ умножить на вектор $\vec{x}=(x_1, x_2, \ldots, x_n)$, то в результате получим 
$$
\begin{align}
\alpha\vec{x} &= \begin{bmatrix}
        \alpha x_1 \\
        \alpha x_2 \\
        \vdots \\
        \alpha x_n
     \end{bmatrix}
\end{align}
$$
Умножение вектора на скалярное значение также называется масштабированием вектора (vector scaling), так как при этом длина вектора увеличивается (или уменьшается если $0 < \alpha < 1$ ) на соответсвтвующее скалярное значение. 

Следующий код релизует умножение вектора $\vec{x}=(1, 2, 3)$ на скалярное значение 5

In [3]:
x = np.array([1, 2, 3])
y = np.zeros_like(x)
a = 5
for i in range(len(x)):
    y[i] = x[i] * a
print(y)

[ 5 10 15]


Однако, на практике писать такой код не стоит. Как было показано в разделе про векторизованные вычисления в NumPy, данный код можно реализовать значительно короче и эффективнее

In [4]:
a * x

array([ 5, 10, 15])

### Сложение векторов
При сложении двух векторов каждый элемент первого вектора складывается соответствующим по индексу элементом второго вектора. Т.е. если нам даны два вектора $\vec{x}=(x_1, x_2, \ldots, x_n)$ и $\vec{y}=(y_1, y_2, \ldots, y_n)$, то при их сложении мы получим следующий вектор
$$
\begin{align}
\vec{x} + \vec{y} &= \begin{bmatrix}
        x_1 + y_1 \\
        x_2 + y_2 \\
        \vdots \\
        x_n + y_n
     \end{bmatrix}
\end{align}
$$
Чтобы сложить два вектора их размер должен быть одинаковым. Следующий пример реализует сложение веткоров на python

In [5]:
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])
z = np.zeros_like(x)
for i in range(len(x)):
    z[i] = x[i] + y[i]
print(z)

[5 7 9]


Реализация с помощью NumPy

In [6]:
x + y

array([5, 7, 9])